export const articles = [
  {
    title:
      "Effects of a low-carbohydrate/high-protein diet on metabolic health in individuals with chronic spinal cord injury: An exploratory analysis of results from a randomized controlled trial",
    altLink: "https://pubmed.ncbi.nlm.nih.gov/36411989",
    link: "https://physoc.onlinelibrary.wiley.com/doi/10.14814/phy2.15501",
    authors: ["Jia Li", "Barbara Gower", "Amie McLain", "Ceren Yarar-Fisher"],
    journal: "Physiological Reports",
    pmid: 36411989,
  },
  {
    title:
      "Effects of a Low-Carbohydrate, High-Protein Diet on Gut Microbiome Composition in Insulin-Resistant Individuals With Chronic Spinal Cord Injury: Preliminary Results From a Randomized Controlled Trial",
    altLink: "https://pubmed.ncbi.nlm.nih.gov/35417758",
    link: "https://www.archives-pmr.org/article/S0003-9993(22)00338-0/fulltext",
    authors: [
      "Jia Li",
      "Casey Morrow",
      "Amie McLain",
      "Erika Womack",
      "Ceren Yarar-Fisher",
    ],
    journal: "Archives of Physical Medicine and Rehabilitation",
    pmid: 35417758,
  },
  {
    title: "Ketogenic regimens for acute neurotraumatic events",
    altLink: "https://pubmed.ncbi.nlm.nih.gov/33445134",
    link: "https://www.sciencedirect.com/science/article/abs/pii/S0958166920301944?via%3Dihub",
    authors: [
      "Ceren Yarar-Fisher",
      "Jia Li",
      "Erika D Womack",
      "Amal Alharbi",
      "Oscar Seira",
      "Kathleen L Kolehmainen",
      "Ward T Plunet",
      "Nima Alaeiilkhchi",
      "Wolfram Tetzlaff",
    ],
    journal: "Current Opinions in Biotechnology",
    pmid: 33445134,
  },
  {
    title:
      "Gut Microbiome Composition and Serum Metabolome Profile Among Individuals With Spinal Cord Injury and Normal Glucose Tolerance or Prediabetes/Type 2 Diabetes",
    altLink: "https://pubmed.ncbi.nlm.nih.gov/34126067",
    link: "https://www.archives-pmr.org/article/S0003-9993(21)00438-X/fulltext",
    authors: [
      "Jia Li",
      "Casey Morrow",
      "Stephen Barnes",
      "Landon Wilson",
      "Erika D Womack",
      "Amie McLain",
      "Ceren Yarar-Fisher",
    ],
    journal: "Archives of Physical Medicine and Rehabilitation",
    pmid: 34126067,
  },
  {
    title:
      "Comparison of the gut microbiome composition among individuals with acute or long-standing spinal cord injury vs. able-bodied controls",
    altLink: "https://pubmed.ncbi.nlm.nih.gov/32496944",
    link: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8890582",
    authors: [
      "Jia Li",
      "William Van Der Pol",
      "Mualla Eraslan",
      "Amie McLain",
      "Hatice Cetin",
      "Baris Cetin",
      "Casey Morrow",
      "Tiffany Carson",
      "Ceren Yarar-Fisher",
    ],
    journal: "The Journal of Spinal Cord Medicine",
    pmid: 32496944,
  },
  {
    title:
      "Evaluation of a ketogenic diet for improvement of neurological recovery in individuals with acute spinal cord injury: a pilot, randomized safety and feasibility trial",
    altLink: "https://pubmed.ncbi.nlm.nih.gov/30275980",
    link: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6155083",
    authors: [
      "Ceren Yarar-Fisher",
      "Adarsh Kulkarni",
      "Jia Li",
      "Paige Farley",
      "Cassandra Renfro",
      "Hammad Aslam",
      "Patrick Bosarge",
      "Landon Wilson",
      "Stephen Barnes",
    ],
    journal: "The Journal of Spinal Cord Medicine",
    pmid: 30275980,
  },
  {
    title:
      "Heightened TWEAK-NF-κB signaling and inflammation-associated fibrosis in paralyzed muscles of men with chronic spinal cord injury",
    altLink: "https://pubmed.ncbi.nlm.nih.gov/26931128",
    link: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4888537",
    authors: [
      "Ceren Yarar-Fisher",
      "C Scott Bickel",
      "Neil A Kelly",
      "Michael J Stec",
      "Samuel T Windham",
      "Amie B McLain",
      "Robert A Oster",
      "Marcas M Bamman",
    ],
    journal: "American Journal of Physiology, Endocrinology and Metabolism",
    pmid: 26931128,
  },
];
